import { Button,VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Temperature Converter";
    preferred-width: 640px;
    preferred-height: 64px;
    min-width: 450px;
    min-height: 48px;

    //Perperites
    in-out property <int> celsius: 0;
    in-out property <int> fahrenheit: 32;

    HorizontalBox {
        celsius_edit := LineEdit {
            text: "\{root.celsius}";
            horizontal-alignment: center;
            edited(text) => {
                root.celsius = text.to-float();
                root.fahrenheit = text.to-float() * 9.0 / 5.0 + 32;
                fahrenheit_edit.text = root.fahrenheit;
            }
        }

        Text {
            text: "Celsius =";
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        fahrenheit_edit := LineEdit {
            text: "\{root.fahrenheit}";
            horizontal-alignment: center;
            edited(text) => {
                root.fahrenheit = text.to-float();
                root.celsius = (text.to-float() - 32) * 5.0 / 9.0;
                celsius_edit.text = root.celsius;
            }
        }

        Text {
            text: "Fahrenheit";
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
